### ISSUE TITLE
[Ideas] Upload to userstyles.world & reduce file size

### ISSUE THREAD

**Issue by Gitleptune** [b4skyx/discord-serenade#1]
Upload to https://userstyles.world so Stylus install is only a few clicks, plus you see how many times it's installed :). It is made by some of the stylus developers and is open source and fast.

Remove empty lines so it loads a few picoseconds faster or provide a [minified](https://cssnano.co) version which will actually have a noticeable difference.

Really pretty theme btw!

**Comment by b4skyx** [comment]
Thanks for the suggestions! Uploaded the theme to userstyles.
I think I'll create a separate minified version of this css as I do not want to compromise the readability.
